/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_gold_gym;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import static gestion_gold_gym.table_pas_paiement.jTable_user;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JK.otmane
 */
public class Gestion_user extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    User u=new User();
     DefaultTableModel model;
     ImageIcon icon;
    public Gestion_user() throws ClassNotFoundException, SQLException {
        initComponents();
        u.fillUserTable(jTable_user, "");
        model=(DefaultTableModel)jTable_user.getModel();
         jTable_user.setRowHeight(40);
        jTable_user.setGridColor(Color.black);
        jTable_user.setShowGrid(true);
        jTable_user.setSelectionBackground(Color.BLUE);
          err_nom.setVisible(false);
        err_pernom.setVisible(false);
        err_cin.setVisible(false);
        err_date_ins.setVisible(false);
        err_numero_ins.setVisible(false);
        err_phone.setVisible(false);
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(jRadioButton3);
        bg1.add(jRadioButton4);
        icon=new ImageIcon("src/image/barbell.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_pernom = new javax.swing.JTextField();
        jTextField_numero_ins = new javax.swing.JTextField();
        jTextField_cin = new javax.swing.JTextField();
        jTextField_phone = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jDateChooser_date = new com.toedter.calendar.JDateChooser();
        edit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        err_nom = new javax.swing.JLabel();
        err_numero_ins = new javax.swing.JLabel();
        err_pernom = new javax.swing.JLabel();
        err_cin = new javax.swing.JLabel();
        err_phone = new javax.swing.JLabel();
        err_date_ins = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filename_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        JLabel_firstname5 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_user = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pernom :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numéro ins :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cin :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date ins :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prix :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Paiement :");

        jTextField_numero_ins.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numero_insKeyTyped(evt);
            }
        });

        jTextField_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phoneKeyTyped(evt);
            }
        });

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Paiement");

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Pas Paiement");

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("80DH");

        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("100DH");

        edit.setBackground(new java.awt.Color(51, 51, 51));
        edit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-update-30.png"))); // NOI18N
        edit.setText("Modifier");
        edit.setIconTextGap(8);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-cancel-30.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setIconTextGap(8);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        err_nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_nom.setForeground(new java.awt.Color(204, 0, 0));
        err_nom.setText("* Nom required fields");

        err_numero_ins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_numero_ins.setForeground(new java.awt.Color(204, 0, 0));
        err_numero_ins.setText("* Numéro inscription required fields");

        err_pernom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_pernom.setForeground(new java.awt.Color(204, 0, 0));
        err_pernom.setText("* Pernom required fields");

        err_cin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_cin.setForeground(new java.awt.Color(204, 0, 0));
        err_cin.setText("* Cin required fields");

        err_phone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_phone.setForeground(new java.awt.Color(204, 0, 0));
        err_phone.setText("* Phone required fields");

        err_date_ins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err_date_ins.setForeground(new java.awt.Color(204, 0, 0));
        err_date_ins.setText("* Date inscription required fields");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Upload Photo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        JLabel_firstname5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLabel_firstname5.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_firstname5.setText("Entrez la valeur à rechercher :");

        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("GESTION ABONNEMENT");

        jTable_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "PERNOM", "NUMBER_INS", "CIN", "PHONE", "DATE_INS", "PRIX", "PAIEMENT", "PHOTO"
            }
        ));
        jTable_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_userMouseClicked(evt);
            }
        });
        jTable_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_userKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_user);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id :");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_image.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_image.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-client-20.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(filename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit))
                        .addComponent(jTextField_pernom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_cin)
                        .addComponent(jTextField_numero_ins)
                        .addComponent(jTextField_phone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton2))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(err_date_ins))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(err_phone))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(err_cin))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(err_numero_ins))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(err_pernom)))
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(err_nom))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addContainerGap(602, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabel_firstname5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLabel_firstname5)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(err_nom)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(err_pernom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_pernom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(err_numero_ins))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jTextField_numero_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(err_cin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(err_phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(err_date_ins))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(edit)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        try {
          
         jTable_user.setModel(new DefaultTableModel(null,new Object[]{"ID","NOM","PERNOM","NUMBRE_INS","CIN","PHONE","DATE_INS","PRIX","PAIEMENT","PHOTO"}));
          u.fillUserTable(jTable_user,jTextField_search.getText());
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gestion_user.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Gestion_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTextField_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_searchKeyTyped

    private void jTextField_numero_insKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numero_insKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_numero_insKeyTyped

    private void jTextField_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_phoneKeyTyped

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        err_nom.setVisible(false);
        err_pernom.setVisible(false);
        err_cin.setVisible(false);
        err_date_ins.setVisible(false);
        err_numero_ins.setVisible(false);
        err_phone.setVisible(false);
        if(jTextField_nom.getText().equals("")){
            err_nom.setVisible(true);
        }else if(jTextField_pernom.getText().equals("")){
            err_pernom.setVisible(true);
        }else if(jTextField_numero_ins.getText().equals("")){
            err_numero_ins.setVisible(true);
        }else if(jTextField_cin.getText().equals("")){
            err_cin.setVisible(true);
        }else if(jTextField_phone.getText().equals("")){
            err_phone.setVisible(true);
        }else if(jDateChooser_date.getDate()==null){
            err_date_ins.setVisible(true);
        }else{
            try {
                int id=Integer.valueOf(jTextField_id.getText());
                String nom =jTextField_nom.getText();
                String pernom=jTextField_pernom.getText();
                Integer number_ins=Integer.valueOf(jTextField_numero_ins.getText().toString());
                String cin =jTextField_cin.getText();
                String phone=jTextField_phone.getText();
                String paiement="paiement";
                String prix="80";
                if(jRadioButton2.isSelected()){
                    paiement="pas paiement";

                }
                if(jRadioButton4.isSelected()){
                    prix="100";
                }
                SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                String date_ins=dateFormat.format(jDateChooser_date.getDate());
                String photo=filename_txt.getText();
                    u.insertdeleteupdate('u', id, nom, pernom, number_ins, cin, phone, date_ins, prix, paiement,photo);
                    MainFram.jLabel2.setText("Le Nombre De personne Abonné ="+Integer.toString(MyFunction.DataCount("user")));
                    MainFram.jLabel3.setText("Le nombre de personnes qui doivent payer ="+Integer.toString(MyFunction.DataCountToday()));
                    MainFram.jLabel4.setText("Le Nombre De Personne Pas Paiement ="+Integer.toString(MyFunction.DataCountPasPaiement()));
                    MainFram.jLabel6.setText(" Nombre d'abonnés : "+Integer.toString(MyFunction.DataCountabonne()));
                    jTextField_id.setText("");
                    jTextField_nom.setText("");
                    jTextField_pernom.setText("");
                    jTextField_numero_ins.setText("");
                    jTextField_cin.setText("");
                    jTextField_phone.setText("");
                    filename_txt.setText("");
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                    jRadioButton3.setSelected(false);
                    jRadioButton4.setSelected(false);
                    jDateChooser_date.setDate(Date.from(Instant.now()));
                    jTable_user.setModel(new DefaultTableModel(null,new Object[]{"ID","NOM","PERNOM","NUMBRE_INS","CIN","PHONE","DATE_INS","PRIX","PAIEMENT","PHOTO"}));
                    u.fillUserTable(jTable_user,"");
                    jLabel_image.setIcon(ResizeImage(""));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
    }//GEN-LAST:event_editActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter =new FileNameExtensionFilter("*.images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selecFile=file.getSelectedFile();
           String path = selecFile.getAbsolutePath();
           filename_txt.setText(path);
           jLabel_image.setIcon(ResizeImage(path));
          
        }else if(result==JFileChooser.CANCEL_OPTION){
            System.out.println("PAS de sélection de fichier");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public ImageIcon ResizeImage(String ImagePath){
        jLabel_image.setVisible(true);
        ImageIcon icon=new ImageIcon(ImagePath);
        Image img=icon.getImage();
        Image newImg=img.getScaledInstance( jLabel_image.getWidth(),  jLabel_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        return image;
    }
    /************************rowIndex****************************/ 
     int rowIndex;
     /************************************************************/
    private void jTable_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_userMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modell=(DefaultTableModel)jTable_user.getModel();
        rowIndex=jTable_user.getSelectedRow();
        if(modell.getValueAt(rowIndex,8).toString().equals("paiement")){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }else{
            jRadioButton2.setSelected(true);
            jRadioButton1.setSelected(false);
        }
        if(modell.getValueAt(rowIndex,7).toString().equals("80")){
            jRadioButton3.setSelected(true);
            jRadioButton4.setSelected(false);
        }else{
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(true);
        }
        jTextField_id.setText(modell.getValueAt(rowIndex, 0).toString());
        jTextField_nom.setText(modell.getValueAt(rowIndex, 1).toString());
        jTextField_pernom.setText(modell.getValueAt(rowIndex, 2).toString());
        jTextField_numero_ins.setText(modell.getValueAt(rowIndex, 3).toString());
        jTextField_cin.setText(modell.getValueAt(rowIndex, 4).toString());
        jTextField_phone.setText(modell.getValueAt(rowIndex, 5).toString());
        try {
            Date date_ins=new SimpleDateFormat("yyyy-MM-DD").parse(modell.getValueAt(rowIndex, 6).toString());
            jDateChooser_date.setDate(date_ins);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        filename_txt.setText(modell.getValueAt(rowIndex,9).toString());
        String path=filename_txt.getText();
       
        jLabel_image.setIcon(ResizeImage(path));
    }//GEN-LAST:event_jTable_userMouseClicked

    private void jTable_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_userKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_UP ||evt.getKeyCode()== KeyEvent.VK_DOWN ){
          rowIndex=jTable_user.getSelectedRow();
        if(model.getValueAt(rowIndex,8).toString().equals("paiement")){
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }else{
            jRadioButton2.setSelected(true);
            jRadioButton1.setSelected(false);
        }
        if(model.getValueAt(rowIndex,7).toString().equals("80")){
            jRadioButton3.setSelected(true);
            jRadioButton4.setSelected(false);
        }else{
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(true);
        }
        jTextField_id.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_nom.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_pernom.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_numero_ins.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField_cin.setText(model.getValueAt(rowIndex, 4).toString());
        jTextField_phone.setText(model.getValueAt(rowIndex, 5).toString());
        try {
            Date date_ins=new SimpleDateFormat("yyyy-MM-DD").parse(model.getValueAt(rowIndex, 6).toString());
            jDateChooser_date.setDate(date_ins);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        filename_txt.setText(model.getValueAt(rowIndex,9).toString());
        String path=filename_txt.getText();
       
        jLabel_image.setIcon(ResizeImage(path));
        }
    }//GEN-LAST:event_jTable_userKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gestion_user().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Gestion_user.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestion_user.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_firstname5;
    private javax.swing.JButton edit;
    private javax.swing.JLabel err_cin;
    private javax.swing.JLabel err_date_ins;
    private javax.swing.JLabel err_nom;
    private javax.swing.JLabel err_numero_ins;
    private javax.swing.JLabel err_pernom;
    private javax.swing.JLabel err_phone;
    private javax.swing.JTextField filename_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_user;
    private javax.swing.JTextField jTextField_cin;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_numero_ins;
    private javax.swing.JTextField jTextField_pernom;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
